CREATE DATABASE HelmetShop
Go
USE HelmetShop;
Go
CREATE TABLE KHACHHANG(
	MAKH INT IDENTITY (1,1) PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NULL,
	SDT VARCHAR(20) NOT NULL,
	TRANGTHAI BIT NOT NULL
)
CREATE TABLE NHANVIEN(
	MANV INT IDENTITY (1,1) PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH INT NOT NULL,
	EMAIL VARCHAR(50) NULL,
	SDT VARCHAR(20) NOT NULL,
	DIACHI NVARCHAR(50) NULL,
	VAITRO BIT NOT NUll,
	TRANGTHAI BIT NOT NULL
)
CREATE TABLE HTTHANHTOAN(
	MAHTTT INT IDENTITY (1,1) PRIMARY KEY,
	TENHTTT NVARCHAR(50) NOT NULL,
	TRANGTHAI BIT NOT NULL
)
CREATE TABLE MAUSAC(
	MAMAU INT IDENTITY (1,1) PRIMARY KEY,
	TENMAU NVARCHAR(50) NOT NULL,
	TRANGTHAI BIT NOT NULL
)
CREATE TABLE SIZE(
	MASIZE INT IDENTITY (1,1) PRIMARY KEY,
	TENSIZE NVARCHAR(50) NOT NULL,
	TRANGTHAI BIT NOT NULL
)
CREATE TABLE LOAIHANG(
	MALH INT IDENTITY (1,1) PRIMARY KEY,
	TENLH NVARCHAR(50) NOT NULL,
	TRANGTHAI BIT NOT NULL
)
CREATE TABLE NHACC(
	MANCC INT IDENTITY (1,1) PRIMARY KEY,
	TENNCC NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50) NULL,
	TRANGTHAI BIT NOT NULL
)
CREATE TABLE DANHMUC(
	MADM INT IDENTITY (1,1) PRIMARY KEY,
	TENDM NVARCHAR(50) NOT NULL,
	MANCC INT NOT NULL,
	TRANGTHAI BIT NOT NULL,
	FOREIGN KEY (MANCC) REFERENCES NHACC 
)
CREATE TABLE KHUYENMAI(
	MAKM INT IDENTITY (1,1) PRIMARY KEY,
	TENKM NVARCHAR(50) NOT NULL,
	NGAYBD DATETIME NOT NULL,
	NGAYKT DATETIME NOT NULL,
	GIAMGIA FLOAT NOT NULL,
	TRANGTHAI BIT NOT NULL,
	GHICHU NVARCHAR(50) NULL,
)
CREATE TABLE CTSANPHAM(
	MASP VARCHAR(10) PRIMARY KEY,
	MALH INT NOT NULL,
	MASIZE INT NOT NULL,
	MAMAU INT NOT NULL,
	MADM INT NOT NULL,
	DONGIA MONEY NOT NULL,
	SOLUONG INT NOT NULL,
	TRANGTHAI BIT NOT NULL,
	GHICHU NVARCHAR(50) NULL,
	FOREIGN KEY (MALH) REFERENCES LOAIHANG,
	FOREIGN KEY (MASIZE) REFERENCES SIZE,
	FOREIGN KEY (MAMAU) REFERENCES MAUSAC,
	FOREIGN KEY (MADM) REFERENCES DANHMUC
)
CREATE TABLE SANPHAM_KHUYENMAI(
	MASP VARCHAR(10) NOT NULL,
	MAKM INT NOT NULL,
	TRANGTHAI BIT NOT NULL,
	FOREIGN KEY (MASP) REFERENCES CTSANPHAM,
	FOREIGN KEY (MAKM) REFERENCES KHUYENMAI,
	PRIMARY KEY(MASP,MAKM)
)
CREATE TABLE HOADON(
	MAHD INT IDENTITY (1,1) PRIMARY KEY,
	MAKH INT NOT NULL,
	MAHTTT INT NOT NULL,
	MANV INT NOT NULL,
	NGAYTAO DATETIME NOT NULL,
	TRANGTHAI INT NOT NULL,
	TIENSHIP MONEY NULL,
	TONGTIEN MONEY NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(50) NULL
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN,
	FOREIGN KEY (MAHTTT) REFERENCES HTTHANHTOAN
)
CREATE TABLE CTHOADON(
	MAHD INT NOT NULL,
	MASP VARCHAR(10) NOT NULL,
	SOLUONG INT NOT NULL,
	DONVI NVARCHAR(10) NOT NULL,
	DONGIA MONEY NOT NULL,
	THANHTIEN MONEY NOT NULL,
	TRANGTHAI BIT NULL,
	FOREIGN KEY (MASP) REFERENCES CTSANPHAM,
	FOREIGN KEY (MAHD) REFERENCES HOADON,
	PRIMARY KEY(MASP,MAHD)

)
SELECT *FROM SANPHAM_KHUYENMAI

